# Generated by Django 4.0.5 on 2022-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.PositiveIntegerField(),
        ),
    ]
